have the set-up page for admin and the userManagement portion for admins
BearGrappler/cnyStore pull request #70
Opened 2016-09-16 22:15 UTC by BearGrappler

2016-09-16 22:26 UTC, nrod80 commented on server/app/routes/users/index.js
> +router.get('/findUsers', function(req, res, next){
maybe make this: router.get('/', function(....?

2016-09-16 22:26 UTC, nrod80 commented on browser/js/admins-only/admins-only.js
> +        console.log(user)
lots of console.logs here

2016-09-16 22:27 UTC, nrod80 commented on browser/js/admins-only/admins-factory.js
> +                    return arrayOfUsers.data;
console logs

2016-09-16 22:27 UTC, nrod80 commented on server/app/routes/users/index.js
> +    console.log('you hit the req /api/findUsers' , req.data)
console.log

2016-09-16 22:28 UTC, nrod80 requested changes
Remove the extraneous console.logs and make the routes/users more RESTful

2016-09-16 22:30 UTC, clocasto approved these changes

2016-09-16 22:30 UTC, nrod80 approved these changes

2016-09-17 02:02 UTC, curiousYi reviewed
These changes look good, I will keep in mind the suggestion to change it to '/' but I think it's ok for now.

2016-09-17 02:38 UTC, merged